#include "MainComponent.h"
#include "Banners.h"
#include "CLI.h"

#include <ftxui/component/component.hpp>
#include <ftxui/dom/elements.hpp>
#include <match-tty/assets/common.h>
#include <match-tty/assets/components.h>
#include <match-tty/game/GameBoardState.h>
#include <match-tty/game/ScoreBar.h>
#include <match-tty/game/TimeBar.h>

#include <memory>
#include <string>

MainComponent::MainComponent(ftxui::ScreenInteractive& screen, cli_options opts)
    : screen_(screen), options_(std::move(opts))
{
    welcome_sel_ = 0;
}

void MainComponent::startGame()
{
    gameover_sel_ = 0;
    time_bar_.reset();
    game_ = std::make_unique<GameBoardState>(
        options_.rows, options_.cols, options_.frame_dur_ms,
        options_.auto_swap_back,
        GameBoardState::defaultGenerate, options_.time_gain,
        options_.penalty_secs);
    time_bar_ = std::make_unique<TimeBar>();
    game_->setTimeBar(time_bar_.get());
    time_bar_->start(options_.game_time_secs, screen_);
    score_bar_ = std::make_unique<ScoreBar>(options_.cols);
    game_->setScoreBar(score_bar_.get());

    if (!game_grid_) {
        game_grid_ = mtty::algo::make_interactive_grid(
            game_->rows(), game_->cols(),
            [this](size_t r, size_t c, bool focused, bool a) {
                return game_->RenderPin(r, c, focused, a);
            },
            [this](std::pair<size_t, size_t> src, std::pair<size_t, size_t> tgt) {
                game_->TriggerSwap(src, tgt, screen_);
            });
        Add(game_grid_);
    }
    was_over_ = false;
    state_ = GameState::PLAYING;
}

ftxui::Element MainComponent::renderWelcome()
{
    auto banner = renderBanner(welcome_banner, ftxui::Color::YellowLight);
    auto buttons = ftxui::hbox({
        ftxui::filler(),
        renderButton("Start", welcome_sel_ == 0),
        ftxui::text("  "),
        renderButton("Quit", welcome_sel_ == 1),
        ftxui::filler(),
    });
    return ftxui::vbox({
        ftxui::vbox({
            banner,
            ftxui::separator(),
            ftxui::text("Match 3 or more same adjacent pins to trigger an elimination. Matches are generated by swapping neighbour pins.") | ftxui::hcenter | ftxui::dim,
            ftxui::text("Use arrow keys for navigation, <space> for start pin selection and arrow keys again for determining the neighbour pin to swap with.") | ftxui::hcenter | ftxui::dim,
            ftxui::text("1 eliminated pin = 1 score + some time bonus. 3 unsuccessful swaps = 5 seconds of penalty.") | ftxui::hcenter | ftxui::dim,
            ftxui::text("") | ftxui::hcenter | ftxui::dim,
            ftxui::text("← → or h/l to select · ENTER to confirm") | ftxui::hcenter | ftxui::dim,
            buttons,
        }) | ftxui::vcenter,
    }) | ftxui::border;
}

ftxui::Element MainComponent::renderPlaying()
{
    if (time_bar_->getRemainingTime() <= 0 && !was_over_) {
        was_over_ = true;
        time_bar_->stop();
        gameover_sel_ = 0;
        state_ = GameState::GAME_OVER;
        return renderGameOver();
    }

    auto now = std::chrono::steady_clock::now();
    game_->UpdateAnimationTimeline(screen_);
    auto grid_elem = game_grid_->Render();
    game_->TryInsertNextFrame(screen_);

    size_t fil_rows_cnt = game_->isVerticalSwap() && game_->isAnimating() ? 1 : 5;
    ftxui::Element grid_and_bar = ftxui::vbox({
        grid_elem,
        score_bar_->Render(),
        ftxui::text("🏆 Score: " + std::to_string(score_bar_->getScore()))
            | ftxui::hcenter,
    });

    ftxui::Element grid_area = ftxui::vbox({
        ftxui::text("🎮 --- MATCH-TTY --- 🎮") | ftxui::hcenter,
        ftxui::separator(),
        mtty::vertical_spacer(fil_rows_cnt),
        ftxui::hbox({
            ftxui::filler(),
            grid_and_bar,
            ftxui::filler(),
        }),
        mtty::vertical_spacer(fil_rows_cnt),
    });

    return ftxui::vbox({
        ftxui::hbox({
            ftxui::filler(),
            grid_area,
            time_bar_->Render(static_cast<int>(game_->rows() * 3)),
            ftxui::filler(),
        }),
        [&]() -> ftxui::Element {
            std::string alert = game_->getAlert();
            if (!alert.empty())
                return ftxui::text("  " + alert + "  ") | ftxui::bold
                    | ftxui::color(ftxui::Color::YellowLight) | ftxui::hcenter;
            return ftxui::text("");
        }(),
    }) | ftxui::border;
}

ftxui::Element MainComponent::renderGameOver()
{
    std::string final_score = std::to_string(score_bar_ ? score_bar_->getScore() : 0);
    return ftxui::vbox({
        ftxui::vbox({
            renderBanner(gameover_banner_line1, ftxui::Color::RedLight),
            renderBanner(gameover_banner_line2, ftxui::Color::RedLight),
            ftxui::separator(),
            ftxui::text("🏆 Final Score: " + final_score) | ftxui::hcenter | ftxui::bold,
            ftxui::hbox({
                ftxui::filler(),
                renderButton("Retry", gameover_sel_ == 0),
                ftxui::text("  "),
                renderButton("Quit", gameover_sel_ == 1),
                ftxui::filler(),
            }),
        }) | ftxui::vcenter,
    }) | ftxui::border;
}

ftxui::Element MainComponent::OnRender()
{
    switch (state_) {
    case GameState::WELCOME:  return renderWelcome();
    case GameState::PLAYING:  return renderPlaying();
    case GameState::GAME_OVER: return renderGameOver();
    }
    return ftxui::text("");
}

bool MainComponent::OnEvent(ftxui::Event e)
{
    if (state_ == GameState::WELCOME) {
        if (e == ftxui::Event::ArrowLeft || e == ftxui::Event::Character('h')) {
            welcome_sel_ = (welcome_sel_ == 0) ? 1 : 0;
            return true;
        }
        if (e == ftxui::Event::ArrowRight || e == ftxui::Event::Character('l')) {
            welcome_sel_ = (welcome_sel_ == 0) ? 1 : 0;
            return true;
        }
        if (e == ftxui::Event::Return) {
            if (welcome_sel_ == 0) startGame();
            else screen_.Exit();
            return true;
        }
        return true;
    }
    if (state_ == GameState::GAME_OVER) {
        if (e == ftxui::Event::ArrowLeft || e == ftxui::Event::Character('h')) {
            gameover_sel_ = (gameover_sel_ == 0) ? 1 : 0;
            return true;
        }
        if (e == ftxui::Event::ArrowRight || e == ftxui::Event::Character('l')) {
            gameover_sel_ = (gameover_sel_ == 0) ? 1 : 0;
            return true;
        }
        if (e == ftxui::Event::Return) {
            if (gameover_sel_ == 0) startGame();
            else screen_.Exit();
            return true;
        }
        return true;
    }
    return ComponentBase::OnEvent(e);
}
